### ISSUE TITLE
Problems with Travis

### ISSUE THREAD

**Issue by ldweeks** [warhornmedia/warhorn-classics-book-template#1]
After installing Travis on my CLI as you directed [here](https://warhornmedia.github.io/warhorn-classics-book-template/01-Basic-instructions.html), I tried to add my personal access token. Here's what I got:

```
Outdated CLI version, run `gem install travis`.
Detected repository as warhornmedia/buchanan-doctrine-of-justification, is this correct? |yes| yes
not logged in, please run travis login --pro
ldweeks@MacBook-Pro-3 buchanan-doctrine-of-justification % travis login --pro
Outdated CLI version, run `gem install travis`.
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: lucas@beggarsborn.com
Password for lucas@beggarsborn.com: *********
ldweeks has not granted Travis CI the required permissions, please log in via travis-ci.com
ldweeks@MacBook-Pro-3 buchanan-doctrine-of-justification % 
```

Giving up for now.

**Comment by ldweeks** [comment]
I logged in to travis-ci.com and authorized everything and ran the command again, and it seemed to work. So I will now try to update the instructions.

**Comment by jtbayly** [comment]
I was assuming that since I gave permission to my account, and I have access to all Warhorn repos, that you wouldn’t need to. Sorry about that.

**Comment by jtbayly** [comment]
Let’s close when we get the documentation fixed.

**Comment by jtbayly** [comment]
Done with Travis. Closing.
